feat/Testes-Concluidos
Grupo-6-PI/Back-End-SpringBoot pull request #17
Opened 2024-09-09 23:31 UTC by Zuull21

2024-09-10 12:05 UTC, DaviRdaSilva requested changes

2024-09-10 12:05 UTC, DaviRdaSilva commented on src/main/kotlin/school/sptech/projetotfg/service/RelatorioFinanceiroService.kt
Como assim a variavel calendarioService e do tipo ModelMapper?

2024-09-10 12:22 UTC, Zuull21 commented on src/main/kotlin/school/sptech/projetotfg/service/RelatorioFinanceiroService.kt
Meu Deus, como isso aconteceu? Vou ajeitar no horário de almoço

2024-09-11 20:26 UTC, DaviRdaSilva approved these changes

2024-09-11 20:26 UTC, merged