Refactor/quadrante-cadastro
Grupo-6-PI/Back-End-SpringBoot pull request #3
Opened 2024-08-13 23:41 UTC by Zuull21

2024-08-14 12:37 UTC, DaviRdaSilva requested changes
Todos os campos de PRIMARY KEY não podem ser nulos, então e pra ficar mais ou menos assim (private var id:Long), parar de iniciar com valor nulo nos contrutores, só declarar a variavél e pronto

2024-08-19 20:56 UTC, DaviRdaSilva commented
Porque fechou o PR? e deletou a Branch?
________________________________
De: Julio Cesar ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:53
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: DAVI RODRIGUES DA SILVA . ***@***.***>; Review requested ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Closed #3<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3>.

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#event-13935741042>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYHOUU6ZNJQIYKV2YYRI7FTZSJLNJAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTHEZTKNZUGEYDIMQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-08-19 21:00 UTC, Zuull21 commented
Não consegui entrar, não estava aparecendo nem que ela existia pelo bash nem pelo terminal, ai fui testar pra deletar e acabou que foi, não sei se fiz merda, desculpa ai, jaja subo o outro pull request
________________________________
De: Davi R Da Silva ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:56
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: JULIO CESAR DE SANTANA DAHI . ***@***.***>; State change ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Porque fechou o PR? e deletou a Branch?
________________________________
De: Julio Cesar ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:53
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: DAVI RODRIGUES DA SILVA . ***@***.***>; Review requested ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Closed #3<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3>.

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#event-13935741042>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYHOUU6ZNJQIYKV2YYRI7FTZSJLNJAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTHEZTKNZUGEYDIMQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#issuecomment-2297441850>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A536GPZPKBODZMPBBFJG4JTZSJLYVAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2DCOBVGA>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-08-19 21:01 UTC, DaviRdaSilva commented
Da o clone denovo, porque já reabri o PR

________________________________
De: Julio Cesar ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 18:01
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: DAVI RODRIGUES DA SILVA . ***@***.***>; State change ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Não consegui entrar, não estava aparecendo nem que ela existia pelo bash nem pelo terminal, ai fui testar pra deletar e acabou que foi, não sei se fiz merda, desculpa ai, jaja subo o outro pull request
________________________________
De: Davi R Da Silva ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:56
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: JULIO CESAR DE SANTANA DAHI . ***@***.***>; State change ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Porque fechou o PR? e deletou a Branch?
________________________________
De: Julio Cesar ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:53
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: DAVI RODRIGUES DA SILVA . ***@***.***>; Review requested ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Closed #3<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3>.

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#event-13935741042>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYHOUU6ZNJQIYKV2YYRI7FTZSJLNJAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTHEZTKNZUGEYDIMQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#issuecomment-2297441850>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A536GPZPKBODZMPBBFJG4JTZSJLYVAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2DCOBVGA>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#issuecomment-2297448047>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYHOUU7YDCJUCVQLL5PWIKLZSJMIZAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2DQMBUG4>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-08-19 21:05 UTC, Zuull21 commented
Feito! Jajá o pull request ta por ai
[Saiba o significado do emoji de continência no WhatsApp - Portal 6]
________________________________
De: Davi R Da Silva ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 18:02
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: JULIO CESAR DE SANTANA DAHI . ***@***.***>; State change ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Da o clone denovo, porque já reabri o PR

________________________________
De: Julio Cesar ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 18:01
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: DAVI RODRIGUES DA SILVA . ***@***.***>; State change ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Não consegui entrar, não estava aparecendo nem que ela existia pelo bash nem pelo terminal, ai fui testar pra deletar e acabou que foi, não sei se fiz merda, desculpa ai, jaja subo o outro pull request
________________________________
De: Davi R Da Silva ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:56
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: JULIO CESAR DE SANTANA DAHI . ***@***.***>; State change ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Porque fechou o PR? e deletou a Branch?
________________________________
De: Julio Cesar ***@***.***>
Enviado: segunda-feira, 19 de agosto de 2024 17:53
Para: Grupo-6-PI/Back-End-SpringBoot ***@***.***>
Cc: DAVI RODRIGUES DA SILVA . ***@***.***>; Review requested ***@***.***>
Assunto: Re: [Grupo-6-PI/Back-End-SpringBoot] Refactor/quadrante-cadastro (PR #3)


Closed #3<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3>.

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#event-13935741042>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYHOUU6ZNJQIYKV2YYRI7FTZSJLNJAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTHEZTKNZUGEYDIMQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#issuecomment-2297441850>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A536GPZPKBODZMPBBFJG4JTZSJLYVAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2DCOBVGA>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#issuecomment-2297448047>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYHOUU7YDCJUCVQLL5PWIKLZSJMIZAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2DQMBUG4>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://github.com/Grupo-6-PI/Back-End-SpringBoot/pull/3#issuecomment-2297449991>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A536GP7OB3QJD7LHIOST3XLZSJMNRAVCNFSM6AAAAABMPHQA3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJXGQ2DSOJZGE>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-08-19 21:27 UTC, merged